# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("lib", __dir__)
require "manticore/client/version"

Gem::Specification.new do |spec|
  spec.name = "manticore-client"
  spec.version = Manticore::Client::VERSION
  spec.platform = Gem::Platform::RUBY
  spec.authors = ["OpenAPI-Generator"]
  spec.email = ["subbota@gmail.com"]
  spec.homepage = "https://github.com/numbata/manticore-client"
  spec.summary = "Autogenerated Manticore Search client"
  spec.description = "Сlient for Manticore Search. "
  spec.license = "MIT"
  spec.required_ruby_version = ">= 2.7"
  spec.metadata = {
    "bug_tracker_uri" => "#{spec.homepage}/issues",
    "changelog_uri" => "#{spec.homepage}/blob/v#{spec.version}/CHANGELOG.md",
    "homepage_uri" => spec.homepage,
    "source_code_uri" => spec.homepage
  }

  spec.add_runtime_dependency "zeitwerk"
  spec.add_runtime_dependency "faraday", ">= 1.0.1", "< 3.0"
  spec.add_runtime_dependency "faraday-multipart"
  spec.add_runtime_dependency "marcel"

  spec.add_development_dependency "rspec", "~> 3.6", ">= 3.6.0"

  spec.files = `git ls-files`.split("\n")

  spec.executables = []
  spec.require_paths = ["lib"]
end
