=begin
#Manticore Search Client

#Сlient for Manticore Search. 

The version of the OpenAPI document: 5.0.0
Contact: info@manticoresearch.com
Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Manticore::Client::KnnQuery
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Manticore::Client::KnnQuery do
  let(:instance) { Manticore::Client::KnnQuery.new }

  describe 'test an instance of KnnQuery' do
    it 'should create an instance of KnnQuery' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Manticore::Client::KnnQuery)
    end
  end

  describe 'test attribute "field"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "k"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "query_vector"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "doc_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "ef"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "filter"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
