=begin
#Manticore Search Client

#Сlient for Manticore Search. 

The version of the OpenAPI document: 5.0.0
Contact: info@manticoresearch.com
Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Manticore::Client::MatchAll
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Manticore::Client::MatchAll do
  let(:instance) { Manticore::Client::MatchAll.new }

  describe 'test an instance of MatchAll' do
    it 'should create an instance of MatchAll' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Manticore::Client::MatchAll)
    end
  end

  describe 'test attribute "_all"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["{}"])
      # validator.allowable_values.each do |value|
      #   expect { instance._all = value }.not_to raise_error
      # end
    end
  end

end
