=begin
#Manticore Search Client

#Сlient for Manticore Search. 

The version of the OpenAPI document: 5.0.0
Contact: info@manticoresearch.com
Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Manticore::Client::Range
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Manticore::Client::Range do
  let(:instance) { Manticore::Client::Range.new }

  describe 'test an instance of Range' do
    it 'should create an instance of Range' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Manticore::Client::Range)
    end
  end

  describe 'test attribute "lt"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "lte"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "gt"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "gte"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
