=begin
#Manticore Search Client

#Сlient for Manticore Search. 

The version of the OpenAPI document: 5.0.0
Contact: info@manticoresearch.com
Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Manticore::Client::ResponseErrorDetails
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Manticore::Client::ResponseErrorDetails do
  let(:instance) { Manticore::Client::ResponseErrorDetails.new }

  describe 'test an instance of ResponseErrorDetails' do
    it 'should create an instance of ResponseErrorDetails' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Manticore::Client::ResponseErrorDetails)
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "reason"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "table"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
